name: Submit Article
description: Use this form to submit an article for review.
title: "[Article Submission] Your Article Title"
labels:
  - article
  - submission
body:
  - type: markdown
    attributes:
      value: |
        ## Basic Information
        Please provide the following details about your article submission.

  - type: input
    id: title
    attributes:
      label: Article Title
      description: Provide a title for your article.
      placeholder: "Enter your article title here"

  - type: markdown
    attributes:
      value: |
        ## Article Content and Review

  - type: textarea
    id: summary
    attributes:
      label: Article Summary
      description: Summarize the article's key points.
      placeholder: "Enter a brief summary"

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category your article fits into.
      options:
        - Technology
        - Business
        - Health
        - Other

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](link/to/coc)
          required: true

  