name: Assign Issue to Creator



on:

  issues:

    types: [opened]



jobs:

  assign_to_creator:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/github-script@latest

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:

          github-token: ${{ secrets.GITHUB_TOKEN }}

          script: |

            github.issues.update({

              issue_number: context.payload.issue.number,

              assignees: [context.actor]

            })
